### ISSUE TITLE
Locked tabs are unlocked after relaunch

### ISSUE THREAD

**Issue by mypointofview** [tabwrangler/tabwrangler#102]
I thought a locked tab is like a "pinned tab" that remains always immune from being closed. Unfortunately this is currently not so. Can you fix this? 

I'm using the latest Google Chrome and latest Tab Wrangler plugin as of 2016-FEB-20.

–martin

**Comment by ssorallen** [comment]
I agree this should happen. Thanks for pointing this out.

**Comment by jay3fer** [comment]
I see that this issue is still hanging around from 2016, making me lose hope that it will ever be fixed.  I installed last week only to discover this "feature." Needing to re-lock my necessary tabs every single time I restart is basically driving me crazy.  I will probably have to stop using this add-in as a result, and whoever is developing this should definitely make preserving the locked status a higher priority!

TabWrangler version 6.1.5
Chrome version 68.0.3440.106 (Official Build) (64-bit)

**Comment by ssorallen** [comment]
@jay3fer I can appreciate the desire more features and bugfixes, but this extension has been built by developers in there free time with no intention of receiving payment. There's no tracking, no personal data storage or transmission, and it's entirely free. We build this because we enjoy it, and although of course we want to ship the best software we can, issues like this will go unattended.

I am happy to work on new features when I have time and to talk with people that are having issues, but coming in with such a negative tone and saying you'll have to stop using this add-in is not helpful. If this issue is so important, I am happy to review a pull request if you want to work on the feature.

**Comment by jay3fer** [comment]
@ssorallen 
Appreciate the quick reply, and I wasn't saying that as a threat, and I'm sorry it came across that way.  It's a terrific add-in that I was happy to discover, and of course kudos to the team who has worked on it.  The idea that I might contribute to the project is somewhat hilarious, so I'll just sit back and let you folks do what you do best.
Cheers.

**Comment by ssorallen** [comment]
I'm looking at implementing this soon, and I believe it's the same as #130. I am going to close this issue and track the dev in that issue, so please see that issue to know when this feature makes it into a release.
