### ISSUE TITLE
Countdown via tab title

### ISSUE THREAD

**Issue by eorroe** [tabwrangler/tabwrangler#123]
I've seen this on other extensions when I found yours, but a 20s (or configurable) countdown showing in the beginning of each tab title would be nice

**Comment by ssorallen** [comment]
Thanks for the idea! Would the countdown make you click to that tab? What would you want to do if you saw the countdown appear on one of the tabs?

**Comment by eorroe** [comment]
Perhaps click on it reminding you to keep it open because you forgot to mark it as never to close or something.

**Comment by ssorallen** [comment]
Changing at tab's title would require injecting a content script into the page in order to set `document.title`. Tab Wrangler does not ask for access to page content, and I don't think it ever should. That is too invasive the the purpose of this extension.

This feature is out of scope of the extension because it would require a permission that I would prefer the extension did not require.
