### ISSUE TITLE
Cannot close a tab that has a PDF file

### ISSUE THREAD

**Issue by j-rahman** [tabwrangler/tabwrangler#146]
For example, open [this PDF document](https://courses.edx.org/c4x/MITx/8.EFTx/asset/images_ImagesForWiki_QCDSummaryForWiki.pdf) on a tab and try to close it using _tabwrangler_.

**Comment by ssorallen** [comment]
Thanks for the issue.

I am able to close that PDF document with Tab Wrangler. Can you give some more information: are you trying to close it manually with the keyboard shortcut? Are you expecting it to close automatically?

**Comment by j-rahman** [comment]
Happens every time with me. I am using it with Google-Chrome on Xubuntu 16.04 LTS, if that helps. I tried closing the tab by right-clicking and choosing to close from the context menu. 

![tabwrangler](https://user-images.githubusercontent.com/24459756/28784524-fb53e1c0-7613-11e7-92fa-a7bacde44f40.png)

**Comment by ssorallen** [comment]
Aha, it's from the context menu. Yes that is broken for me too, thanks for pointing that out. I'll get that fixed.

**Comment by ssorallen** [comment]
This is due to Chrome's PDF Viewer. Its PDF Viewer is an extension itself, and although the URL bar shows an internet address, the contents of the page are rendered by the extension. The [`chrome.contextMenus`](https://developer.chrome.com/apps/contextMenus#type-ContextType) API returns information about an extension tab rather than the original tab when you click one of Tab Wrangler's context menu items.

I commented on a Chromium bug about ["Internal PDF viewer's context menu shows extension entries"](https://bugs.chromium.org/p/chromium/issues/detail?id=431340) to see whether this is intended functionality or whether Tab Wrangler should prevent showing its context menu on PDF tabs.

Right now there is no fix for this issue from what I can see.

**Comment by ingorichter** [comment]
Perhaps this issue should be closed and tagged with `totrack` since there is nothing we can do about it right now.

**Comment by ssorallen** [comment]
@ingorichter Is the idea that open tasks are ones you know have a possible fix or work that can be done?

**Comment by ingorichter** [comment]
@ssorallen Yes. We use this at work to make sure we take care of actionable items and put everything that we can't control out of our way. We don't close the issue, but we mark it `totrack`. We have a section in our reports about tracked issues so we don't lose them.

**Comment by ssorallen** [comment]
@ingorichter Sounds good to me. Closing for now with the "totrack" label.
