### ISSUE TITLE
Can only restore 15 tabs at a time

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [tabwrangler/tabwrangler#148]
In the corral are 126 tabs.

Check the **Select all tabs** box and the Restore button grays out.

Individually check the boxes and the **Restore** button is functional UNTIL you check the 16th box, then it grays out again. What's the point of only restoring a dozen at a time?
_Ain't nobody got time for that!_

I want the ENTIRE session restored most of the time.
And, if I had multiple windows with tabs, I want the session restored that way unless I choose to open all tabs in one window. Those tabs were in multiple windows for a reason - If I'd wanted them combined I would have opened them in one window myself.

**Comment by ssorallen** [comment]
Restoring 126 tabs at once is almost guaranteed to crash Chrome! That's a ton of network requests at once. I added the 15 tab limit because of https://github.com/jacobSingh/tabwrangler/issues/109, but the limit is admittedly arbitrary.

I could change that to a warning saying opening many new tabs at once could cause performance problems or even crash your browser. That'd be nicer than preventing it entirely.

**Comment by ssorallen** [comment]
RE: restoring to the correct windows

https://github.com/jacobSingh/tabwrangler/issues/138 tracks opening tabs in the correct window

**Comment by GitTheHellOutaHere** [comment]
I don't normally have that many tabs open (usually less than 80), but Chrome & Safari haven't crashed because of it.

IMO tabs should either be restored but not loaded, or loaded one at a time instead of all at once.

That's the way a good session manager works to restore tabs when a browser is opened.
I don't see why TW can't function the same way, to prevent overloading the network when opening an abundance of tabs.
