### ISSUE TITLE
high-resolution icon

### ISSUE THREAD

**Issue by ghost** [tabwrangler/tabwrangler#180]
plz support "4k quality icon" and "Do not suspend tabs that are playing audio" mode

**Comment by ssorallen** [comment]
Thanks for the issue.

"4k quality icon": Do you mean Tab Wrangler's own icon?

"Do not suspend tabs that are playing audio" was added in [v5.6.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v5.6.0). Check the options tab for the option "Don't close tabs that are playing audio".

**Comment by simple-is-best** [comment]
oh! i can find this. thanks for your work.
sorry my english. The app icon appears dim on the Retina monitor.

**Comment by ssorallen** [comment]
No problem. Thanks for the note about the icon. The app does need a higher quality icon. I will leave this issue open to address that.

**Comment by ssorallen** [comment]
I would like to address this as part of #168.

**Comment by ssorallen** [comment]
@simple-is-best Since you said English is not your first language, it would be great if you could contribute some translations in your native language! Any contributions, large or small, would be appreciated. I'm happy to help you if you'd like to contribute.

Documentation for contributing translations: https://github.com/tabwrangler/tabwrangler/blob/master/CONTRIBUTING.md#contributing-translations

**Comment by simple-is-best** [comment]
@ssorallen oh! good job. i will do it. my language is korean.

**Comment by KTamas** [comment]
@ssorallen i, for one, am fond of the current icon and i think changing it would cause a lot of confusion. what did you use to create it? do you still have the original file?

**Comment by ssorallen** [comment]
Rolling this into #437 for a full branding refresh.
