### ISSUE TITLE
More than 500 tabs?

### ISSUE THREAD

**Issue by k2l8m11n2** [tabwrangler/tabwrangler#200]
Would it be possible to make the limit higher?

**Comment by Voknehzyr** [comment]
For what? :disappointed_relieved:

**Comment by k2l8m11n2** [comment]
For extreme taboholics of course!

**Comment by quintrino** [comment]
To clarify, you mean the maximum number of tabs that can be stored in the corral?

**Comment by ssorallen** [comment]
I think Chrome's own history (chrome://history/) is a better use case for this sort of storage than Tab Wrangler, but I do understand why you would want to keep a running history of everything TW has done.

What sort of tabs were closed so long ago that you want to retrieve them? Does Tab Wrangler often close hundreds of tabs for you each day? If we can get to the root of your use case, maybe there's a more interesting solution than just adding more tab storage.

**Comment by rizwank** [comment]
To this end, I have extreme fomo when I go over 500 and I lose a link I stored (granted 2 years ago) in perpetuity. For me, not having lost it permanently is the goal for over 500 (or some other method of archiving.) Or holding a wrangle at 500 so it forces me to prune.

thanks!

**Comment by ssorallen** [comment]
Maybe at the bottom of the Tab Corral it could say, "Looking for other tabs? Check Chrome's/Firefox's History ->" with a link to the browser's own history viewer. I do still think the browser's own history viewer is a better UI for this because it's a full view of what you've visited and not just a list of tabs that Tab Wrangler closed.

Also, maybe the Tab Corral chould be based on a time rather than an absolute number, i.e. "Remove tabs from the corral after 30 days, after 3 months, after 6 months, etc.".

**Comment by quintrino** [comment]
I do like the idea of an option of if you exceed your corral you can have it stop wrangling rather than losing your oldest tabs.

**Comment by davask** [comment]
I m a bookmarkhoolic and yesterday I open 250 tabs for some work I m doing and forgot to close then. I had 36 tabwrangled which were completly different for the 250 and I wanted to keep it like that.
This morning from my 250 open tabs only 6 were still open, 100 tabwrangled and the 36 gone for ever.

I believe we might want a save in bookmark option so in case of anything wrong or if the max limit from tabwragled is reach we can still access it from the bookmark.

What do you think ?

**Comment by ssorallen** [comment]
@davask I'm happy to figure out a way to make Tab Wrangler work for you. We could raise the 500 limit. Anecdotally, 500 tabs take up about [5% of TW's storage quota][0]. I would give a wide margin of error for that so, I'd say 10% or so is needed for 500 tabs.

My reluctance to increasing this limit is that at any finite limit I can imagine someone saying, X is not enough can we raise it to Y? We could continue raising the limit for a long time, but I think we could find better ways to help you use your browser than saying, "go check that list of 10,000 tabs closed by Tab Wrangler."

[0]: https://github.com/tabwrangler/tabwrangler/issues/83#issuecomment-405246861

**Comment by davask** [comment]
I agree on not upgrading the tab wrangler limit as in my point of view tab wrangler is kind of a tool for on going topic, like I m looking around for new shoes for 2 days, as long as I haven t finish this search I don t need to make my tab wrangler saved as bookmark.
It is kind of pre bookmark tools to me. 
I hope you understand what I mean, i my point of view a prebookmarker has a high value.

with my way of doing things I have reach more than 9k bookmarks and I m actually thinking about a tool to make them useful, so in our case, loosing 100 tabs is quite a problem.

So I will definitly be very happy to get a closed tab wrangler (maybe as bookmarks).

Thx for answering

**Comment by ssorallen** [comment]
Okay, I doubled the limit to 1,000. It's in master and will go in the next release, likely v6.1.0.

What do y'all think?

**Comment by ssorallen** [comment]
The limit is up to 1,000 in [v6.1.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v6.1.0). That will use a max of 20% (conservative estimate, likely far less) of Tab Wrangler's storage allocation. If 1,000 is still not enough, let's revisit this and provide a better solution.

**Comment by pirate** [comment]
I don't know about ya'll, but 1000 is nowhere near enough for me, that's like 4 days worth of closed tabs! Why is it limited at all? What's the point of restricting it below the system disk space limits?

**Comment by ssorallen** [comment]
@pirate The default storage size is 5MB for extensions unless they request the ["unlimitedStorage" permission](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Unlimited_storage). It would certainly be possible to request "unlimitedStorage" for Tab Wrangler, but Tab Wrangler would slowly be implementing the History feature that browsers already provide.

Why would you want unlimited Tab Wrangler storage over using your browser's built in History tool?

**Comment by pirate** [comment]
Because browser history is a different concept entirely, it's every single page every visited sorted by *date visited*. Tag wrangler history is only tabs that have been closed by the extension sorted by *date closed*. I use tab wrangler history to scroll back through tabs that Tab Wrangler has closed so that I can reopen important ones, for tabs that have been open for weeks they'll be long gone in history.

**Comment by MartinHammarstedt** [comment]
I agree that the browser history serves an entirely different purpose. My history consists almost entirely of websites I've closed because I'm done with them, and I usually never intend to open them again (articles I've read, videos I've watched, etc). Tab Wrangler on the other hand contains sites I intend to get back to and do something with, I just haven't had the time yet. At the same time they are not sites I plan on reading/using more than once, or I would have bookmarked them instead.

I actually stopped using Tab Wrangler a while ago since I was afraid of losing tabs when I was getting close to the limit. For my own sanity it's probably best for there to be a limit, but I don't like how the limit works. I don't know if it has changed since then, but I'd rather see that it stopped closing my tabs when the limit is reached, than removing the older closed tabs from the list.
