### ISSUE TITLE
inconsistent wrangling

### ISSUE THREAD

**Issue by petebrag** [tabwrangler/tabwrangler#203]
some tabs are wrangled, some are not and there's no consistency.
This makes the extension pretty much useless.
What am I missing?

**Comment by ssorallen** [comment]
Thanks for the issue. Can you provide more information? What do your settings look like? Which tabs were wrangled, and which ones were wrangled when you didn't expect?

**Comment by petebrag** [comment]
Here's a video  explaining the issue:

http://www.youtube.com/watch?v=c5OM1pOQDo4

it's only 3 minutes long.

Thanks,

Pete

**Comment by ssorallen** [comment]
Thanks a lot for the video and the narration. I think I understand.

* The title in Tab Wrangler will always be the title you see on the tab. Tab Wrangler uses that same value, so if Google Sheets doesn't change the tab title when you switch between the sheets then Tab Wrangler won't be able to see the new title.
* Tabs only show up in Tab Wrangler if Tab Wrangler auto-closed them. Closing tabs normally by clicking the 'X' or using Cmd+W does not add the tab to Tab Wrangler, and that is intentional. TW only shows tabs that it auto-closed because they were inactive according to your settings.
  * You can configure a new shortcut to always close tabs using Tab Wrangler! Open Tab Wrangler, go to "Options", and scroll to the bottom. Click "Configure these shortcuts" to configure a keyboard shortcut that will close the current tab and save it to Tab Wrangler.

Everything in your video seems to be working as designed in Tab Wrangler, but I see why the functionality is confusing. If you have any suggestions to make the functionality clearer, I would be happy to make changes. If you have any other issues, please let me know as well.
