### ISSUE TITLE
[Firefox] Tab sessions not being restored

### ISSUE THREAD

**Issue by edjroot** [tabwrangler/tabwrangler#224]
Similarly to #125, tab sessions are not being restored on Firefox, although they are on Chrome.

**Comment by ssorallen** [comment]
It looks like this is due to Chrome storing `session.lastModified` in seconds whereas Firefox stores it as milliseconds. The documentation all says milliseconds, but Chrome is breaking here. `CorralTab` is already accounting for Chrome's mistake: https://github.com/tabwrangler/tabwrangler/blob/95c0cc8af7c1b83500260a86939ea9cf900a5c5f/app/js/CorralTab.js#L116-L118

That function should check whether the value is small enough to be seconds and behave accordingly. Then it will work for both Chrome and for Firefox.
