### ISSUE TITLE
Feature Request: Don't Close Tabs Playing Audio

### ISSUE THREAD

**Issue by darklordabc** [tabwrangler/tabwrangler#233]
This could be a podcast, youtube, any other site that you are listening to. Would be a nice feature, as sometimes I have a tab open in the background and it gets closed abruptly.

**Comment by ssorallen** [comment]
This feature exists! If you go to *Options* and check the checkbox in this screenshot, tabs playing audio will not be closed by Tab Wrangler.

<img width="418" alt="audio-tabs" src="https://user-images.githubusercontent.com/29612/40247095-d5a227dc-5afd-11e8-99ad-59e0e006e1d2.png">

I'm going to close this because the feature seems to be implemented as you would like. If you have any issues with it, let me know and please re-open this issue.

**Comment by darklordabc** [comment]
You win this round

**Comment by ssorallen** [comment]
@darklordabc Although the fact that you didn’t know the feature existed is problematic. I’ve looked at that options page a lot, so it’s difficult for me to know whether it’s easy to use and discover. This is a point in favor of it being too confusing.
