### ISSUE TITLE
[Feature Request] Restore Tabs by Random

### ISSUE THREAD

**Issue by Kilo19** [tabwrangler/tabwrangler#235]
One reason to use Tab Wrangler is to not dealing with deciding to keep the tabs open. (http://www.jacobsingh.name/content/tab-wrangler-or-how-i-stopped-thrashing-and-learned-close-my-tabs). However, as time goes on, more and more tabs accumulate in the corral and they are rarely restored for the same reason (tabs that are obviously not needed are deleted from the corral). Would you like to add a feature that randomly restores a tab (or a configurable number of tabs) that can be filtered by searches? For example, randomly restore 3 tabs from the entire corral or from tabs that contain the word "review".

**Comment by quintrino** [comment]
Why at random and not just in order?

**Comment by Kilo19** [comment]
@quintrino To give older tabs equal chance.

**Comment by ssorallen** [comment]
If you need a random number to re-open old tabs, do you really need those tabs? :) Since you can already do this by searching and then selecting tabs yourself, I don't think there's a need to add a specific "Random" button. This might have a similar feeling to Google's "I'm Feeling Lucky"? I'm not sure though, I only rarely dig through Tab Wrangler's history and find something I needed.

I'm open to pull requests of course, but I don't think I will add this myself. I am going to close for now, but if you'd like to work on it and submit a PR please re-open and assign to yourself. I'll be happy to see what you come up with.
