### ISSUE TITLE
Question regarding resources

### ISSUE THREAD

**Issue by XxX-Force** [tabwrangler/tabwrangler#260]
I've never used github before, so apologies if I'm putting this in the wrong place.
This looks like an extremely impressive and full featured extension. Unfortunately for me, I have some mental problem where I am a "tab hoarder". My solution for this has been, when I reach 100 or so tabs, I will "bookmark all tabs" and then throw them into a folder that is named with the date. Of course, I never look at those bookmarks again lmao .. but I know that my precious tabs are protected forever. I like the idea of using this, to free up resources as I browse, but at the end I would have to open all tabs and then bookmark them. When Tab Wrangler closes a tab, does it actually kill the Chrome process in task manager, freeing up resources? Thank you.﻿

**Comment by ssorallen** [comment]
This is a fine place to ask a question, thanks for posting.

Tab Wrangler actually closes the tab, so any resources it was using are cleaned up. Tab Wrangler stores a list of tabs it has closed so you can re-open them if you like. It's worth trying out to see if it can help with your tab hoarding because it worked for me. I rarely realize Tab Wrangler is doing its job because I don't need the tabs it closes.

There's currently no equivalent to "bookmark all tabs", but a similar feature was requested in #170.

I'll close this since there is no action to be taken here, but feel free to post more,
