### ISSUE TITLE
Do not close tabs with an active input.

### ISSUE THREAD

**Issue by pthfdr-42** [tabwrangler/tabwrangler#264]
Do not close any tab that has an active input, like [what I am doing](https://user-images.githubusercontent.com/42509223/55680921-baf01f80-5952-11e9-8419-21adfa719a79.png).
It is annoying that you have to type in a Reddit post or a long form, go to other sites to fill in the data only to find that the tab containing the form is closed.

**Comment by ssorallen** [comment]
Thanks for creating the issue.

We could make this an opt-in feature that would request the extra permission only if you enable the feature. Currently, Tab Wrangler can information about tabs you have open but does not have permission to read any information inside the actual tabs; and that is intentional. Detecting whether there are changes on a page requires an extension to inject scripts into the page, and that is something I'd like to avoid for Tab Wrangler as a default option.

**Comment by pthfdr-42** [comment]
No. I am not talking about saving the contents locally. I am talking about that the extension should detect that something is going on in some tabs and not automatically closing them by mistake.
