### ISSUE TITLE
Hotkey for tab locks

### ISSUE THREAD

**Issue by Bubbha-Gautama** [tabwrangler/tabwrangler#281]
The main problem with Tabwrangler is it's too time-consuming to lock tabs, and that really eats up all the gains you get from deleting old tabs. 

Some times you need to keep tabs, but if you need to open the program and locate the tab first to do that, it's too complicated to be practical. A simple hotkey in the tab itself would be much better.

**Comment by KTamas** [comment]
I started working on it but chrome starts somehow glitching when i add a second hotkey to the manifest and i have yet to figure out what the fuck is happening because it does not make any sense at the moment.

**Comment by ssorallen** [comment]
I haven't yet implemented this because I'd like to be able to give visual feedback when a tab is locked. Other extensions change their icons based on the current focused tab, so Tab Wrangler could do the same.

1. if Tab Wrangler is disabled, show circle with cross through it icon
2. else if current tab is locked, show locked icon
3. else show default icon

**Comment by ssorallen** [comment]
This was implemented in commit https://github.com/tabwrangler/tabwrangler/commit/75d6d47b40d8eb03f2b6950284a50fa3b428769e and released into v6.10.0.

**Comment by Slyger** [comment]
i mean why wait untill you can visual feedback when a tab is locked? why not just add hotkey now and deal with that later?

**Comment by ssorallen** [comment]
@Slyger The feature is already built and in [v6.10.1](https://github.com/tabwrangler/tabwrangler/releases/tag/v6.10.1). It was released to Firefox but not to Chrome, I will release it now.

**Comment by Slyger** [comment]
Ah ok cos in the chrome extention store its version 6.9.0 last updated March 2021
