### ISSUE TITLE
Tabs disappearing

### ISSUE THREAD

**Issue by aztec506** [tabwrangler/tabwrangler#288]
I've been using TabWrangler with Firefox for years.  It has done exactly what I wanted - shut down the dozens of inactive tabs I have open but remembering what they were.
All of a sudden and out of the blue TabWrangler is not remembering tabs if I close Firefox for the night.  Last night I left Firefox open to see if closing it the night before was the problem.  It saved 4-5 open tabs but not the dozens of tabs that were already in TabWrangler.
I've gone through the settings for both Firefox and TabWrangler to see if maybe something had changed but I could see nothing that would explain the problem.
Any ideas on what may be causing that?

**Comment by ssorallen** [comment]
Thank you for the report, and I apologize for the data loss. I thought this issue had been permanently fixed in https://github.com/tabwrangler/tabwrangler/issues/241, but that sadly does not seem to be the case.

The latest release added more data to the sync storage, and now it seems the library doing the syncing is once again an issue and causing data loss. This is disheartening to see again. I will debut this soon and answer in this thread.

Apologies again for the data loss, I spent a lot of time the previous time this happened but sadly look like I put too much trust in the syncing library again.

**Comment by edwh** [comment]
Thanks for the useful addon.  I'm also seeing data loss, of the tabs I have locked.  

The only tabs I want to lock at the ones I have set as my startup tab.  So for me two things would help:

- If possible, auto-lock the tabs you have set as startup tabs
- Failing that, an option to select all the currently open tabs for locking.  Then I can lock them all with a single click.

**Comment by KTamas** [comment]
@aztec506 @edwh is this still an issue?

**Comment by edwh** [comment]
Yes, very regularly.

**Comment by hlmaldon** [comment]
Yes

**Comment by ssorallen** [comment]
Since this issue continues to exist, the use of [`redux-persist`](https://github.com/rt2zz/redux-persist) likely needs to be eliminated in Tab Wrangler. It has been the source of data loss and apparently still is.

After [migrating Tab Wrangler to Manifest v3](https://github.com/tabwrangler/tabwrangler/issues/350), this issue can be higher priority.

**Comment by ssorallen** [comment]
`redux-persist` was removed in v7 in favor of `react-query` and persistence to storage that I have written as opposed to `redux-persist`'s unmaintained persistence layer.

Closing as "fixed" from many changes since this bug was opened. Please re-open if you see this issue again.
