### ISSUE TITLE
Idea: Color of the tab reflects its 'age'. 

### ISSUE THREAD

**Issue by re404** [tabwrangler/tabwrangler#290]
**Problem**
I can't visually see which tabs are about to 'die' soon (going to Coral's heaven ;))

**Solution**
It would be nice if the background color of the tab('s label) reflects its age (for example in light shades from light green -fresh-, to yellow -aging- and towards brown -about to die-.
(I have no idea if chrome allows changing this color per tab.)

Thanks! Cheers,
//r

**Comment by ssorallen** [comment]
Thanks for the idea submission.

Changing the appearance of the browser, including its tabs, only appears to be possible via the [`theme` API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme). It does not seem to allow setting different color values per tab.

Extensions that used to be able to do this, like [ColorfulTabs](https://addons.mozilla.org/en-US/firefox/addon/colorfultabs/reviews/) no longer work due to changes in browser APIs.

For the time being it does not appear that TabWrangler will be able to add this functionality.

**Comment by re404** [comment]
Hi @ssorallen,

Thanks for looking into it!

Thinking about possible alternatives (/hacks) ... would it maybe be an option to:
a.  "Inject" a colored dot in the label's title (in between the favicon and the title)  ?
b. "hijack the favicon" by for example layering a 1px or 2px colored line over it that ?
... of changing color reflecting it's age?

//r

**Comment by re404** [comment]
p.s. I use TabWrangler in conjunction with The Great Suspender. I just realized that The Great Suspender makes the favicon semi-transparent after suspending it. Could this be an option?
**c. "alpha-fading" the favicon gradually**

**Comment by re404** [comment]
Related idea:
I have my "**_Auto-close tabs only if I have more than:_**" set to 5. I realized that I tend to drag tabs that I want to keep open to the left so they won't be auto-closed. 
Wouldn't it be great if these **"safe tabs" on the left visually stand out from the "temporary tabs" on the right?**

**Comment by KTamas** [comment]
this is interesting, but not a priority. PRs welcome.

**Comment by ssorallen** [comment]
The browser extension API does not support this currently. Rather than let this request linger many more years, I am closing as "won't fix."
