### ISSUE TITLE
Close tabs in background

### ISSUE THREAD

**Issue by indigoviolet** [tabwrangler/tabwrangler#323]
**Is your feature request related to a problem? Please describe.**

When tabwrangler closes tabs, it can end up switching the active tab. This is jarring and frustrating when I'm working on that tab, writing in an input box for example. 

**Describe the solution you'd like**
Close tabs in the background (ie. without affecting the active tab). If this is not possible, only close tabs when chrome is in the background.

**Comment by marijuanatech** [comment]
Hmm, I've never had it change my active tab - I'll look for it happening now though.

**Comment by KTamas** [comment]
@indigoviolet has this happened since?

**Comment by ssorallen** [comment]
Thanks for creating an issue.

The tab being closed likely had a listener on `beforeunload` (this is how web pages trigger the native "this page has unsaved changes" popup, like in Gmail). That is outside the control of Tab Wrangler and not something TW should be able to circumvent. Having used TW for years at this point, I have experienced that tab switching due to "This page has unsaved changes" but not any other time.

If you experience this tab switching at another time please comment again with the case and reopen the issue.
