### ISSUE TITLE
Does Tab Wrangler reset idle-timer for the current tab every 5 seconds?

### ISSUE THREAD

**Issue by llinfeng** [tabwrangler/tabwrangler#343]
I am new to Tab Wrangler and find the following screenshot a bit confusing:
![TimerRefreshed_tabwrangler](https://user-images.githubusercontent.com/5890407/126230147-f0e0145b-8115-4c52-8c46-11460c82cad0.gif)

Was it the browser that kept updating something on the foreground tab, such that Tab Wrangler refreshes the idle-timer every other five seconds? Or, is it a built-in mechanism for Tab Wrangler to keep the current tab "alive"?

Such "resets" for the idle-timer for the foreground tab is observed both on Google Chrome and Firefox. The frequencies for resets on the two browsers are the same. The idle-timer is reset every 5 seconds for the foreground tab.

**Comment by marijuanatech** [comment]
Yep - it's a function of Tab Wrangler.  Every 5 seconds, it checks for stale tabs to close.

**Comment by llinfeng** [comment]
@marijuanatech Thanks for confirming. Would there be an option to disable such auto-timer for the foreground tab?

One potential use is to close the tab for a Jupyter lab sessions, when one is idle for long. This helps to avoid overwriting conflicts when one load into the session from somewhere else.

**Comment by marijuanatech** [comment]
I think this would be possible.  I apologize though - I don't fully understand what you're wanting to happen.

If the timer is disabled on the foreground tab, I think it will close because it'll be "stale".

Is that what you want? An option allowing Tab Wrangler to close the active tab if it becomes stale?

If you share a bit more information I'll look into it for you.

**Comment by llinfeng** [comment]
Exactly, it helps to close the tab when it is stale for certain amount of time. An alternative is to "tab away" from the stale tab by creating a "New Tab". [This may speak of an additional exception for the idle-timer: for "New Tab" created via Ctrl+T, it is OK to leave the tab _alive_. This alternative approach may help to keep the browser window intact if it is positioned to a fixed location in a multi-monitor setup.]

----

I initially came across Tab Wrangler when logging tons of "Jupyter development hours" using WakaTime's Chrome plugin. For those "active Jupyter hours", I was mostly using an RDP connection to the machine. WakaTime thought those were active coding hours. Currently, I am using a separate timer that does the alternative approach: when I am no longer actively using the Jupyter lab tab, create a new tab (or switch to the new tab if there is one).  This stops WakaTime from logging tons of stale time when the Jupyter lab tab is left in the foreground by itself.

**Comment by marijuanatech** [comment]
Thanks for the info! I'm still getting acquainted with Tab Wrangler so I apologize if I misunderstood something and am giving you wrong info.

So, since the tab is open, it's considered active. There's not anything looking at the content of the tab (by design) to see if it's active or not. It's all based around if it's open or not. Unfortunately, I think that means what you're asking for isn't feasible.

**Comment by llinfeng** [comment]
Fair enough. Glad we are documenting it here, that:
* By design, Tab Wrangler resets the timer on the current tab every 5 seconds, and
* By design, the tab at the forefront will always be active. It won't reach a stale state.

I will stay with my external timer tool then. (It is an AutoHotKey script.)
