### ISSUE TITLE
Fucken SHIT!!!

### ISSUE THREAD

**Issue by kirichenkof** [tabwrangler/tabwrangler#345]
Your app has deleted all my 1200 tabs !! how can I restore them !?

**Comment by RiZKiT** [comment]
Already looked in the [Tab Corral](https://addons.cdn.mozilla.net/user-media/previews/full/201/201369.png)?

**Comment by ssorallen** [comment]
This is free, open source software that I have worked on in my spare time because I want to. Your tone is neither appreciated nor going to get you any useful reply from me.

* Look at https://github.com/tabwrangler/tabwrangler/issues/241#issuecomment-425640668 if Tab Wrangler's Corral is truly empty, you may be able to recover data
* You can always use your browser's own history to navigate old sites you visited

Please consider your tone before posting next time. I will simply close and lock any future issues without responding if they use this same tone.
