### ISSUE TITLE
feat request: Right click -> lock tab

### ISSUE THREAD

**Issue by nol166** [tabwrangler/tabwrangler#455]
**Is your feature request related to a problem? Please describe.**
No problem, just a feature request

**Describe the solution you'd like**
I noticed that some extensions have the ability to add a menu item or two to the right click context menu when right clicking on a tab. It would be nice to have tabwrangler add an option to "lock tab" directly by right clicking on it.

**Describe alternatives you've considered**
You can always lock tabs from the extension's menu, however another option would be cool

**Comment by ssorallen** [comment]
@nol166 You can right click inside a tab to get a Tab Wrangler context menu, but I do not believe Chrome or Firefox allows extensions to add context menu items to actual tab UI elements themselves. If you do find an extension that enables this please let me know. I am going to close this for now because I believe it is technically impossible at the moment.
